#include <assertions.h>
#include <testing.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <float.h>
#include "support_funcs.h"


TEST(test_where_concat_1) {
    int (**where_funcs)(double, double, int) = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    double* arr = malloc(5 * sizeof(double));
    size_t* size = 0;
    double* cond_data_array = malloc(5 * sizeof(double));
    int* cond_array = malloc(5 * sizeof(int));
    size_t operations_ammount = 0;
    int* operations = malloc(5 * sizeof(int));
    double* result = where_concat(NULL, arr, size, cond_data_array, cond_array, operations_ammount, operations);
    double* expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);
}


TEST(test_where_concat) {
    int (**where_funcs)(double, double, int) = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    double* arr = malloc(5 * sizeof(double));
    size_t* size = 0;
    double* cond_data_array = malloc(5 * sizeof(double));
    int* cond_array = malloc(5 * sizeof(int));
    size_t operations_ammount = 0;
    int* operations = malloc(5 * sizeof(int));
    double* result = where_concat(NULL, arr, size, cond_data_array, cond_array, operations_ammount, operations);
    double* expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, NULL, size, cond_data_array, cond_array, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, arr, NULL, cond_data_array, cond_array, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, arr, size, NULL, cond_array, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, arr, size, cond_data_array, NULL, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, arr, size, cond_data_array, cond_array, operations_ammount, NULL);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);
    
    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(NULL, NULL, size, cond_data_array, cond_array, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(NULL, arr, NULL, cond_data_array, cond_array, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(NULL, arr, NULL, cond_data_array, cond_array, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(NULL, arr, size, NULL, cond_array, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(NULL, arr, size, cond_data_array, NULL, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(NULL, arr, size, cond_data_array, cond_array, operations_ammount, NULL);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, NULL, NULL, cond_data_array, cond_array, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, NULL, size, NULL, cond_array, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, NULL, size, cond_data_array, NULL, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, NULL, size, cond_data_array, cond_array, operations_ammount, NULL);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, arr, NULL, NULL, cond_array, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, arr, NULL, cond_data_array, NULL, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, arr, NULL, cond_data_array, cond_array, operations_ammount, NULL);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, arr, size, NULL, NULL, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, arr, size, NULL, cond_array, operations_ammount, NULL);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, arr, size, cond_data_array, NULL, operations_ammount, NULL);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(NULL, NULL, NULL, cond_data_array, cond_array, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(NULL, NULL, size, NULL, cond_array, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(NULL, NULL, size, cond_data_array, NULL, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(NULL, NULL, size, cond_data_array, cond_array, operations_ammount, NULL);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(NULL, arr, NULL, NULL, cond_array, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(NULL, arr, NULL, cond_data_array, NULL, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(NULL, arr, NULL, cond_data_array, cond_array, operations_ammount, NULL);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(NULL, arr, NULL, NULL, cond_array, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(NULL, arr, NULL, cond_data_array, NULL, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(NULL, arr, NULL, cond_data_array, cond_array, operations_ammount, NULL);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(NULL, arr, size, NULL, NULL, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(NULL, arr, size, NULL, cond_array, operations_ammount, NULL);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(NULL, arr, size, cond_data_array, NULL, operations_ammount, NULL);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, NULL, NULL, NULL, cond_array, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, NULL, NULL, cond_data_array, NULL, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, NULL, NULL, cond_data_array, cond_array, operations_ammount, NULL);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, NULL, size, NULL, NULL, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, NULL, size, NULL, cond_array, operations_ammount, NULL);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, NULL, size, cond_data_array, NULL, operations_ammount, NULL);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, arr, NULL, NULL, NULL, operations_ammount, operations);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, arr, NULL, NULL, cond_array, operations_ammount, NULL);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, arr, NULL, cond_data_array, NULL, operations_ammount, NULL);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);

    where_funcs = malloc(1 * sizeof(int(*) (double, double, int))); 
    where_funcs[0] = &bounds; 
    arr = malloc(5 * sizeof(double));
    size = 0;
    cond_data_array = malloc(5 * sizeof(double));
    cond_array = malloc(5 * sizeof(int));
    operations_ammount = 0;
    operations = malloc(5 * sizeof(int));
    result = where_concat(where_funcs, arr, size, NULL, NULL, operations_ammount, NULL);
    expect = NULL;
    assert(result == expect);
    free(where_funcs);
    free(arr);
}
